export const ActionType = {
  FETCH_RECIPE_LIST: 'FETCH_RECIPE_LIST',
  FETCH_RECIPE_ITEM: 'FETCH_RECIPE_ITEM',
  ADD_FAV: 'ADD_FAV',
  REMOVE_FAV: 'REMOVE_FAV',
  ADD_RECIPE: 'ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
};
